// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AUTHORS: typeof import('./../node_modules/typescript/AUTHORS.md')['default']
    CODE_OF_CONDUCT: typeof import('./../node_modules/typescript/CODE_OF_CONDUCT.md')['default']
    FiraSansLISCENSE: typeof import('./../node_modules/vfonts/font-license/FiraSans-LISCENSE.md')['default']
    LatoLISCENSE: typeof import('./../node_modules/vfonts/font-license/Lato-LISCENSE.md')['default']
    Layout: typeof import('./layout/index.vue')['default']
    LICENSE: typeof import('./../node_modules/vite/LICENSE.md')['default']
    Login: typeof import('./views/login.vue')['default']
    Menus: typeof import('./layout/components/Menus.vue')['default']
    Navigation: typeof import('./layout/components/Navigation.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpin: typeof import('naive-ui')['NSpin']
    OpenSansLISCENSE: typeof import('./../node_modules/vfonts/font-license/OpenSans-LISCENSE.md')['default']
    README: typeof import('./../README.md')['default']
    'README.zhCN': typeof import('./../node_modules/naive-ui/README.zh-CN.md')['default']
    RobotoLISCENSE: typeof import('./../node_modules/vfonts/font-license/Roboto-LISCENSE.md')['default']
    RobotoSlabLISCENSE: typeof import('./../node_modules/vfonts/font-license/RobotoSlab-LISCENSE.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SECURITY: typeof import('./../node_modules/typescript/SECURITY.md')['default']
    Views: typeof import('./views/index.vue')['default']
  }
}
